---
run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 120
  goconst:
    min-len: 3
    min-occurrences: 3
  goimports:
    local-prefixes: slackbot.arpa
  funlen:
    lines: 100
    statements: 50
  gocognit:
    min-complexity: 15
  nestif:
    min-complexity: 4
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks: [dupImport, ifElseChain, octalLiteral, whyNoLint]
linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - funlen
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - gocognit
        - gomnd
    # Exclude lll issues for long lines with go:generate
    - linters: [lll]
      source: '^//go:generate '
  max-same-issues: 50
  new: false
severity:
  default-severity: error
  rules:
    - linters: [misspell, gofmt]
      severity: warning
