---
extends: default
rules:
  line-length:
    max: 200
    level: warning
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  braces:
    max-spaces-inside: 1
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  quoted-strings:
    quote-type: any
    required: only-when-needed
    extra-allowed: [\$.*]
ignore: |-
  node_modules/
  deps/
  _build/
  build/
  cover/
  docker/data/
  tmp/
  .env
