[tools]
go = "latest"
golangci-lint = "latest"
pre-commit = "latest"
task = "latest"
uv = "latest"

yamllint = "latest"
"pipx:yamlfix" = "latest"
prettier = "latest"

[settings]
disable_backends = ["asdf"]
pipx_uvx = true
