---
vibecheck:
  good_reactions: [ok]
  good_text: [V I B E C H E C K - P A S S E D]
  bad_reactions: [no_entry]
  bad_text: [V I B E C H E C K - F A I L E D]
chat:
  responses:
    - pattern: hello
      message: Hello there! How can I help you today?
      is_regexp: false
    - pattern: thanks|thank you|thx|ty
      message: You're welcome!
      is_regexp: true
      reactions: ['+1']
    - pattern: .*vibe.*
      is_regexp: true
      reactions: [ok, vibecheck]
    - pattern: \bok\b|\bokay\b
      is_regexp: true
      reactions: [ok]
