---
name: Build and publish bot image

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    paths:
      - bot/**
      - cmd/bot/**
      - .github/workflows/publish-bot.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  REPO: brettinternet/slackbot
  IMAGE_NAME: slackbot
  DESCRIPTION: A Slack bot
  DOCKERFILE: ./docker/bot/prod.Dockerfile

defaults:
  run:
    working-directory: ./

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skipci')"
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,amd64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.actor }}/${{ env.IMAGE_NAME }}
          flavor: latest=auto
          tags: type=ref,event=branch
          labels: |
            org.opencontainers.image.name=${{ env.IMAGE_NAME }}
            org.opencontainers.image.source=https://github.com/${{ env.REPO }}/tree/main/${{ env.IMAGE_NAME }}
            org.opencontainers.image.description=${{ env.DESCRIPTION }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE}}
          platforms: arm64,amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_VERSION=${{ steps.meta.outputs.sha }}
            BUILD_DATE=${{ github.event.repository.updated_at }}
            BUILD_ENVIRONMENT=production
